"""empty message

Revision ID: 53193f583618
Revises: a845ab6fec5c
Create Date: 2021-08-21 14:38:46.889344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53193f583618'
down_revision = 'a845ab6fec5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    # ### end Alembic commands ###
