"""empty message

Revision ID: cfa9573e4102
Revises: 5f0bdeb01e79
Create Date: 2021-08-21 15:52:58.293145

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cfa9573e4102'
down_revision = '5f0bdeb01e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('people', sa.Column('birth_year', sa.String(length=120), nullable=True))
    op.add_column('people', sa.Column('eye_color', sa.String(length=120), nullable=True))
    op.add_column('people', sa.Column('hair_color', sa.String(length=120), nullable=True))
    op.add_column('people', sa.Column('homeworld_id', sa.Integer(), nullable=True))
    op.add_column('people', sa.Column('gender', sa.String(length=120), nullable=True))
    op.add_column('people', sa.Column('height', sa.String(length=120), nullable=True))
    op.add_column('people', sa.Column('mass', sa.String(length=120), nullable=True))
    op.add_column('people', sa.Column('skin_color', sa.String(length=120), nullable=True))
    op.add_column('people', sa.Column('url', sa.String(length=120), nullable=True))
    op.add_column('people', sa.Column('created', sa.String(length=120), nullable=True))
    op.add_column('people', sa.Column('edited', sa.String(length=120), nullable=True))
    op.drop_index('email', table_name='people')
    op.drop_index('email_2', table_name='people')
    op.create_foreign_key(None, 'people', 'planets', ['homeworld_id'], ['id'])
    op.drop_column('people', 'email')
    op.add_column('planets', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('planets', sa.Column('diameter', sa.String(length=120), nullable=True))
    op.add_column('planets', sa.Column('rotation_period', sa.String(length=120), nullable=True))
    op.add_column('planets', sa.Column('orbital_period', sa.String(length=120), nullable=True))
    op.add_column('planets', sa.Column('gravity', sa.String(length=120), nullable=True))
    op.add_column('planets', sa.Column('population', sa.String(length=120), nullable=True))
    op.add_column('planets', sa.Column('climate', sa.String(length=120), nullable=True))
    op.add_column('planets', sa.Column('terrain', sa.String(length=120), nullable=True))
    op.add_column('planets', sa.Column('surface_water', sa.String(length=120), nullable=True))
    op.add_column('planets', sa.Column('url', sa.String(length=120), nullable=True))
    op.add_column('planets', sa.Column('created', sa.String(length=120), nullable=True))
    op.add_column('planets', sa.Column('edited', sa.String(length=120), nullable=True))
    op.drop_index('email', table_name='planets')
    op.drop_index('email_2', table_name='planets')
    op.drop_column('planets', 'email')
    op.add_column('vehicle', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('vehicle', sa.Column('model', sa.String(length=120), nullable=True))
    op.add_column('vehicle', sa.Column('vehicle_class', sa.String(length=120), nullable=True))
    op.add_column('vehicle', sa.Column('manufacturer', sa.String(length=120), nullable=True))
    op.add_column('vehicle', sa.Column('length', sa.String(length=120), nullable=True))
    op.add_column('vehicle', sa.Column('cost_in_credits', sa.String(length=120), nullable=True))
    op.add_column('vehicle', sa.Column('crew', sa.String(length=120), nullable=True))
    op.add_column('vehicle', sa.Column('passengers', sa.String(length=120), nullable=True))
    op.add_column('vehicle', sa.Column('max_atmosphering_speed', sa.String(length=120), nullable=True))
    op.add_column('vehicle', sa.Column('cargo_capacity', sa.String(length=120), nullable=True))
    op.add_column('vehicle', sa.Column('consumables', sa.String(length=120), nullable=True))
    op.add_column('vehicle', sa.Column('url', sa.String(length=120), nullable=True))
    op.add_column('vehicle', sa.Column('created', sa.String(length=120), nullable=True))
    op.add_column('vehicle', sa.Column('edited', sa.String(length=120), nullable=True))
    op.drop_index('email', table_name='vehicle')
    op.drop_index('email_2', table_name='vehicle')
    op.drop_column('vehicle', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('email', mysql.VARCHAR(length=120), nullable=False))
    op.create_index('email_2', 'vehicle', ['email'], unique=False)
    op.create_index('email', 'vehicle', ['email'], unique=False)
    op.drop_column('vehicle', 'edited')
    op.drop_column('vehicle', 'created')
    op.drop_column('vehicle', 'url')
    op.drop_column('vehicle', 'consumables')
    op.drop_column('vehicle', 'cargo_capacity')
    op.drop_column('vehicle', 'max_atmosphering_speed')
    op.drop_column('vehicle', 'passengers')
    op.drop_column('vehicle', 'crew')
    op.drop_column('vehicle', 'cost_in_credits')
    op.drop_column('vehicle', 'length')
    op.drop_column('vehicle', 'manufacturer')
    op.drop_column('vehicle', 'vehicle_class')
    op.drop_column('vehicle', 'model')
    op.drop_column('vehicle', 'name')
    op.add_column('planets', sa.Column('email', mysql.VARCHAR(length=120), nullable=False))
    op.create_index('email_2', 'planets', ['email'], unique=False)
    op.create_index('email', 'planets', ['email'], unique=False)
    op.drop_column('planets', 'edited')
    op.drop_column('planets', 'created')
    op.drop_column('planets', 'url')
    op.drop_column('planets', 'surface_water')
    op.drop_column('planets', 'terrain')
    op.drop_column('planets', 'climate')
    op.drop_column('planets', 'population')
    op.drop_column('planets', 'gravity')
    op.drop_column('planets', 'orbital_period')
    op.drop_column('planets', 'rotation_period')
    op.drop_column('planets', 'diameter')
    op.drop_column('planets', 'name')
    op.add_column('people', sa.Column('email', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.create_index('email_2', 'people', ['email'], unique=False)
    op.create_index('email', 'people', ['email'], unique=False)
    op.drop_column('people', 'edited')
    op.drop_column('people', 'created')
    op.drop_column('people', 'url')
    op.drop_column('people', 'skin_color')
    op.drop_column('people', 'mass')
    op.drop_column('people', 'height')
    op.drop_column('people', 'gender')
    op.drop_column('people', 'homeworld_id')
    op.drop_column('people', 'hair_color')
    op.drop_column('people', 'eye_color')
    op.drop_column('people', 'birth_year')
    op.drop_column('people', 'name')
    # ### end Alembic commands ###
